apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart
  name: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - image: rahmaahmed2002/depi_gp-cart-service:v1
        name: cart-service
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/cart_db
        - name: REDIS_URL
          value: redis://redis:6379
        - name: ACCESS_TOKEN
          value: prod_secret
        - name: PRODUCT_SERVICE_URL
          value: http://product:3002
        
