apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-configmap
data:
  PRODUCT_MONGO_URI: "mongodb://mongodb:27017/product_db"
  CART_MONGO_URI: "mongodb://mongodb:27017/cart_db"
  USER_MONGO_URI: "mongodb://mongodb:27017/user_db"
  PRODUCT_SERVICE_URL: "http://product:3002"
  REDIS_URL: "redis://redis:6379"
